Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================ RESTART: C:\Users\user\Desktop\scrapping.py ================

================ RESTART: C:\Users\user\Desktop\scrapping.py ================

================ RESTART: C:\Users\user\Desktop\scrapping.py ================

================ RESTART: C:\Users\user\Desktop\scrapping.py ================
foxnews.com
sportsbettingdime.com
cnn.com
twnews.co.uk
fox5atlanta.com
arstechnica.com
globalnews.ca
jpost.com
cnn.com
avclub.com
commercialappeal.com
straitstimes.com
lovewhatmatters.com
cnn.com
cnn.com
theguardian.com
wfmz.com
omaha.com
dublin
usatoday.com
bbc.co.uk
nbcnews.com
yenisafak.com
pcgamesn.com
mazech.com
https://old.reddit.com/r/nottheonion/?count=25&after=t3_d9sqoj
26
foxnews.com
koat.com
theguardian.com
channelnewsasia.com
mazechmedia.com
irishtimes.com
cbc.ca
theguardian.com
latimes.com
belfasttelegraph.co.uk
bbc.com
ktla.com
ctvnews.ca
inc.com
bbc.com
foxnews.com
ottawacitizen.com
france24.com
ocregister.com
kwqc.com
cbc.ca
newsweek.com
kcci.com
inquirer.com
arstechnica.com
https://old.reddit.com/r/nottheonion/?count=50&after=t3_d8e4op
51
wqow.com
kentonline.co.uk
arstechnica.com
abcnews
nottinghampost.com
bitterwinter.org
premier.org
wbrz.com
oregonlive.com
bbc.co.uk
guinnessworldrecords.com
avclub.com
nbcdfw.com
fox59.com
hindustantimes.com
eveningexpress.co.uk
kake.com
npr.org
sky.com
archive.org
politico
vancouversun.com
cnn.com
bbc.com
wearecentralpa.com
https://old.reddit.com/r/nottheonion/?count=75&after=t3_d7ir55
76
ctvnews.ca
wgntv.com
wndu.com
wtap.com
cbslocal.com
apnews.com
cnbc.com
time.com
ctvnews.ca
seeker.com
theguardian.com
abcnews
tampabay.com
bbc.co.uk
egamingdesk.com
newsweek.com
theguardian.com
bbc.co.uk
abcnews
nypost.com
themoscowtimes.com
theguardian.com
todayonline.com
ksl.com
theguardian.com
https://old.reddit.com/r/nottheonion/?count=100&after=t3_d5zngr
101
kiwaradio.com
cbslocal.com
nbcnews.com
wsbt.com
cbc.ca
newjerseyglobe.com
theguardian.com
crimerussia.com
nbcnews.com
cbsnews.com
expat-in
thejakartapost.com
abc.net
kpax.com
ktla.com
rmotoday.com
newsweek.com
www.in
wapt.com
theguardian.com
google.com
cnn.com
themoscowtimes.com
japantimes.co
foxnews.com
https://old.reddit.com/r/nottheonion/?count=125&after=t3_d3pk6f
126
arstechnica.com
cbsnews.com
local10.com
abcnews
foxnews.com
nzherald.co
kuwaittimes.net
cnn.com
EW
theguardian.com
thehindu.com
ctvnews.ca
heraldpublicist.com
bbc.co.uk
nzherald.co
reuters.com
syracuse.com
sciencedirect.com
ctvnews.ca
sevendaysvt.com
theguardian.com
fox5sandiego.com
victormatara.com
ksdk.com
bbc.co.uk
https://old.reddit.com/r/nottheonion/?count=150&after=t3_d2oigf
151
bbc.co.uk
wral.com
abcnews
khaleejtimes.com
nottheonion/com
www.in
abc.net
theguardian.com
theguardian.com
cdllife.com
mapleridgenews.com
indianexpress.com
prnewswire.com
channel3000.com
theguardian.com
Traceback (most recent call last):
  File "C:\Users\user\Desktop\scrapping.py", line 35, in <module>
    link = next_page['href']
TypeError: 'NoneType' object is not subscriptable
>>> 
========= RESTART: C:\Users\user\Desktop\FakeNewsVerification\Lol.py =========
Traceback (most recent call last):
  File "C:\Users\user\Desktop\FakeNewsVerification\Lol.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
>>> 
